CRITICAL - 2024-11-25 02:46:02 --> Error: Call to undefined function App\Controllers\setting()
[Method: GET, Route: /]
in APPPATH\Controllers\Home.php on line 13.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 2 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 7 SYSTEMPATH\rewrite.php(44): require_once('X:\\00.templates\\ci4-starter\\public\\index.php')
CRITICAL - 2024-11-25 02:48:32 --> Error: Call to undefined function App\Controllers\setting()
[Method: GET, Route: /]
in APPPATH\Controllers\Home.php on line 13.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 2 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 7 SYSTEMPATH\rewrite.php(44): require_once('X:\\00.templates\\ci4-starter\\public\\index.php')
CRITICAL - 2024-11-25 03:04:06 --> Error: Call to undefined function App\Controllers\setting()
[Method: GET, Route: /]
in APPPATH\Controllers\Home.php on line 13.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 2 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 7 SYSTEMPATH\rewrite.php(44): require_once('X:\\00.templates\\ci4-starter\\public\\index.php')
CRITICAL - 2024-11-25 03:04:08 --> Error: Call to undefined function App\Controllers\setting()
[Method: GET, Route: /]
in APPPATH\Controllers\Home.php on line 13.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 2 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 7 SYSTEMPATH\rewrite.php(44): require_once('X:\\00.templates\\ci4-starter\\public\\index.php')
ERROR - 2024-11-25 03:34:01 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 X:\00.templates\ci4-starter\vendor\codeigniter4\settings\src\Handlers\DatabaseHandler.php(186): CodeIgniter\Database\BaseBuilder->get()
#5 X:\00.templates\ci4-starter\vendor\codeigniter4\settings\src\Handlers\DatabaseHandler.php(51): CodeIgniter\Settings\Handlers\DatabaseHandler->hydrate(NULL)
#6 X:\00.templates\ci4-starter\vendor\codeigniter4\settings\src\Settings.php(59): CodeIgniter\Settings\Handlers\DatabaseHandler->has('Config\\AppJay', 'siteName', NULL)
#7 X:\00.templates\ci4-starter\app\Controllers\Home.php(13): CodeIgniter\Settings\Settings->get('AppJay.siteName')
#8 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Home->index()
#9 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 X:\00.templates\ci4-starter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('X:\\00.templates...')
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 X:\00.templates\ci4-starter\vendor\codeigniter4\settings\src\Handlers\DatabaseHandler.php(186): CodeIgniter\Database\BaseBuilder->get()
#4 X:\00.templates\ci4-starter\vendor\codeigniter4\settings\src\Handlers\DatabaseHandler.php(51): CodeIgniter\Settings\Handlers\DatabaseHandler->hydrate(NULL)
#5 X:\00.templates\ci4-starter\vendor\codeigniter4\settings\src\Settings.php(59): CodeIgniter\Settings\Handlers\DatabaseHandler->has('Config\\AppJay', 'siteName', NULL)
#6 X:\00.templates\ci4-starter\app\Controllers\Home.php(13): CodeIgniter\Settings\Settings->get('AppJay.siteName')
#7 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Home->index()
#8 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 X:\00.templates\ci4-starter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('X:\\00.templates...')
#14 {main}
CRITICAL - 2024-11-25 03:34:01 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `settings`
WHERE `context` IS NULL', [], false)
 3 VENDORPATH\codeigniter4\settings\src\Handlers\DatabaseHandler.php(186): CodeIgniter\Database\BaseBuilder->get()
 4 VENDORPATH\codeigniter4\settings\src\Handlers\DatabaseHandler.php(51): CodeIgniter\Settings\Handlers\DatabaseHandler->hydrate(null)
 5 VENDORPATH\codeigniter4\settings\src\Settings.php(59): CodeIgniter\Settings\Handlers\DatabaseHandler->has('Config\\AppJay', 'siteName', null)
 6 APPPATH\Controllers\Home.php(13): CodeIgniter\Settings\Settings->get('AppJay.siteName')
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('X:\\00.templates\\ci4-starter\\public\\index.php')
ERROR - 2024-11-25 03:34:03 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 X:\00.templates\ci4-starter\vendor\codeigniter4\settings\src\Handlers\DatabaseHandler.php(186): CodeIgniter\Database\BaseBuilder->get()
#5 X:\00.templates\ci4-starter\vendor\codeigniter4\settings\src\Handlers\DatabaseHandler.php(51): CodeIgniter\Settings\Handlers\DatabaseHandler->hydrate(NULL)
#6 X:\00.templates\ci4-starter\vendor\codeigniter4\settings\src\Settings.php(59): CodeIgniter\Settings\Handlers\DatabaseHandler->has('Config\\AppJay', 'siteName', NULL)
#7 X:\00.templates\ci4-starter\app\Controllers\Home.php(13): CodeIgniter\Settings\Settings->get('AppJay.siteName')
#8 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Home->index()
#9 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 X:\00.templates\ci4-starter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('X:\\00.templates...')
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 X:\00.templates\ci4-starter\vendor\codeigniter4\settings\src\Handlers\DatabaseHandler.php(186): CodeIgniter\Database\BaseBuilder->get()
#4 X:\00.templates\ci4-starter\vendor\codeigniter4\settings\src\Handlers\DatabaseHandler.php(51): CodeIgniter\Settings\Handlers\DatabaseHandler->hydrate(NULL)
#5 X:\00.templates\ci4-starter\vendor\codeigniter4\settings\src\Settings.php(59): CodeIgniter\Settings\Handlers\DatabaseHandler->has('Config\\AppJay', 'siteName', NULL)
#6 X:\00.templates\ci4-starter\app\Controllers\Home.php(13): CodeIgniter\Settings\Settings->get('AppJay.siteName')
#7 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Home->index()
#8 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 X:\00.templates\ci4-starter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 X:\00.templates\ci4-starter\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('X:\\00.templates...')
#14 {main}
CRITICAL - 2024-11-25 03:34:03 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `settings`
WHERE `context` IS NULL', [], false)
 3 VENDORPATH\codeigniter4\settings\src\Handlers\DatabaseHandler.php(186): CodeIgniter\Database\BaseBuilder->get()
 4 VENDORPATH\codeigniter4\settings\src\Handlers\DatabaseHandler.php(51): CodeIgniter\Settings\Handlers\DatabaseHandler->hydrate(null)
 5 VENDORPATH\codeigniter4\settings\src\Settings.php(59): CodeIgniter\Settings\Handlers\DatabaseHandler->has('Config\\AppJay', 'siteName', null)
 6 APPPATH\Controllers\Home.php(13): CodeIgniter\Settings\Settings->get('AppJay.siteName')
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('X:\\00.templates\\ci4-starter\\public\\index.php')
ERROR - 2024-11-25 03:56:07 --> mysqli_sql_exception: Table '808_starter.settings' doesn't exist in X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(312): mysqli->query('SELECT *\nFROM `...', 0)
#1 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\settings\src\Handlers\DatabaseHandler.php(186): CodeIgniter\Database\BaseBuilder->get()
#5 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\settings\src\Handlers\DatabaseHandler.php(51): CodeIgniter\Settings\Handlers\DatabaseHandler->hydrate(NULL)
#6 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\settings\src\Settings.php(59): CodeIgniter\Settings\Handlers\DatabaseHandler->has('Config\\AppJay', 'siteName', NULL)
#7 X:\00.templates\ci4-starter\dist\app\Controllers\Home.php(13): CodeIgniter\Settings\Settings->get('AppJay.siteName')
#8 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Home->index()
#9 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 X:\00.templates\ci4-starter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('X:\\00.templates...')
#15 {main}
CRITICAL - 2024-11-25 03:56:07 --> CodeIgniter\Database\Exceptions\DatabaseException: Table '808_starter.settings' doesn't exist
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `settings`
WHERE `context` IS NULL', [], false)
 2 VENDORPATH\codeigniter4\settings\src\Handlers\DatabaseHandler.php(186): CodeIgniter\Database\BaseBuilder->get()
 3 VENDORPATH\codeigniter4\settings\src\Handlers\DatabaseHandler.php(51): CodeIgniter\Settings\Handlers\DatabaseHandler->hydrate(null)
 4 VENDORPATH\codeigniter4\settings\src\Settings.php(59): CodeIgniter\Settings\Handlers\DatabaseHandler->has('Config\\AppJay', 'siteName', null)
 5 APPPATH\Controllers\Home.php(13): CodeIgniter\Settings\Settings->get('AppJay.siteName')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('X:\\00.templates\\ci4-starter\\public\\index.php')
CRITICAL - 2024-11-25 03:56:07 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table '808_starter.settings' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `settings`
WHERE `context` IS NULL')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `settings`
WHERE `context` IS NULL')
 3 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `settings`
WHERE `context` IS NULL', [], false)
 4 VENDORPATH\codeigniter4\settings\src\Handlers\DatabaseHandler.php(186): CodeIgniter\Database\BaseBuilder->get()
 5 VENDORPATH\codeigniter4\settings\src\Handlers\DatabaseHandler.php(51): CodeIgniter\Settings\Handlers\DatabaseHandler->hydrate(null)
 6 VENDORPATH\codeigniter4\settings\src\Settings.php(59): CodeIgniter\Settings\Handlers\DatabaseHandler->has('Config\\AppJay', 'siteName', null)
 7 APPPATH\Controllers\Home.php(13): CodeIgniter\Settings\Settings->get('AppJay.siteName')
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('X:\\00.templates\\ci4-starter\\public\\index.php')
CRITICAL - 2024-11-25 03:56:07 --> [Caused by] mysqli_sql_exception: Table '808_starter.settings' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('SELECT *
FROM `settings`
WHERE `context` IS NULL', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `settings`
WHERE `context` IS NULL')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `settings`
WHERE `context` IS NULL')
 4 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `settings`
WHERE `context` IS NULL', [], false)
 5 VENDORPATH\codeigniter4\settings\src\Handlers\DatabaseHandler.php(186): CodeIgniter\Database\BaseBuilder->get()
 6 VENDORPATH\codeigniter4\settings\src\Handlers\DatabaseHandler.php(51): CodeIgniter\Settings\Handlers\DatabaseHandler->hydrate(null)
 7 VENDORPATH\codeigniter4\settings\src\Settings.php(59): CodeIgniter\Settings\Handlers\DatabaseHandler->has('Config\\AppJay', 'siteName', null)
 8 APPPATH\Controllers\Home.php(13): CodeIgniter\Settings\Settings->get('AppJay.siteName')
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('X:\\00.templates\\ci4-starter\\public\\index.php')
ERROR - 2024-11-25 09:12:16 --> mysqli_sql_exception: Duplicate column name 'first_name' in X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(312): mysqli->query('ALTER TABLE `us...', 0)
#1 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('ALTER TABLE `us...')
#2 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('ALTER TABLE `us...')
#3 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\Forge.php(772): CodeIgniter\Database\BaseConnection->query('ALTER TABLE `us...')
#4 X:\00.templates\ci4-starter\dist\app\Database\Migrations\2024-11-25-083545_AlterTableUsers.php(52): CodeIgniter\Database\Forge->addColumn('users', Array)
#5 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(867): App\Database\Migrations\AlterTableUsers->up()
#6 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(183): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\CLI\BaseCommand.php(119): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Commands\Database\MigrateRefresh.php(87): CodeIgniter\CLI\BaseCommand->call('migrate', Array)
#11 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\MigrateRefresh->run(Array)
#12 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\CLI\BaseCommand.php(119): CodeIgniter\CLI\Commands->run('migrate:refresh', Array)
#13 X:\00.templates\ci4-starter\dist\app\Commands\RefreshCommand.php(61): CodeIgniter\CLI\BaseCommand->call('migrate:refresh', Array)
#14 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\CLI\Commands.php(70): App\Commands\RefreshCommand->run(Array)
#15 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('starter:refresh', Array)
#16 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Boot.php(351): CodeIgniter\CLI\Console->run()
#17 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#18 X:\00.templates\ci4-starter\dist\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#19 {main}
CRITICAL - 2024-11-25 09:12:19 --> Error: Call to a member function insert() on null
[Method: CLI, Route: starter:refresh]
in APPPATH\Database\Seeds\DownloadsSeeder.php on line 95.
 1 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\DownloadsSeeder->run()
 2 APPPATH\Database\Seeds\A1Seeder.php(12): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\DownloadsSeeder')
 3 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\A1Seeder->run()
 4 APPPATH\Database\Seeds\BaseSeeder.php(13): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\A1Seeder')
 5 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\BaseSeeder->run()
 6 APPPATH\Commands\RefreshCommand.php(63): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\BaseSeeder')
 7 SYSTEMPATH\CLI\Commands.php(70): App\Commands\RefreshCommand->run([])
 8 SYSTEMPATH\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('starter:refresh', [])
 9 SYSTEMPATH\Boot.php(351): CodeIgniter\CLI\Console->run()
10 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
11 ROOTPATH\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
ERROR - 2024-11-25 09:21:21 --> mysqli_sql_exception: Table '808_starter.users' doesn't exist in X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(312): mysqli->query('ALTER TABLE `us...', 0)
#1 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('ALTER TABLE `us...')
#2 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('ALTER TABLE `us...')
#3 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\Forge.php(772): CodeIgniter\Database\BaseConnection->query('ALTER TABLE `us...')
#4 X:\00.templates\ci4-starter\dist\app\Database\Migrations\2024-11-25-083545_AlterTableUsers.php(52): CodeIgniter\Database\Forge->addColumn('users', Array)
#5 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(867): App\Database\Migrations\AlterTableUsers->up()
#6 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(183): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\CLI\BaseCommand.php(119): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Commands\Database\MigrateRefresh.php(87): CodeIgniter\CLI\BaseCommand->call('migrate', Array)
#11 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\MigrateRefresh->run(Array)
#12 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\CLI\BaseCommand.php(119): CodeIgniter\CLI\Commands->run('migrate:refresh', Array)
#13 X:\00.templates\ci4-starter\dist\app\Commands\RefreshCommand.php(61): CodeIgniter\CLI\BaseCommand->call('migrate:refresh', Array)
#14 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\CLI\Commands.php(70): App\Commands\RefreshCommand->run(Array)
#15 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('starter:refresh', Array)
#16 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Boot.php(351): CodeIgniter\CLI\Console->run()
#17 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#18 X:\00.templates\ci4-starter\dist\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#19 {main}
ERROR - 2024-11-25 09:21:21 --> mysqli_sql_exception: Table '808_starter.users' doesn't exist in X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `us...', 0)
#1 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\shield\src\Models\UserModel.php(270): CodeIgniter\Model->insert(Object(CodeIgniter\Shield\Entities\User), false)
#8 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Shield\Models\UserModel->insert(Object(CodeIgniter\Shield\Entities\User), false)
#9 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\shield\src\Models\UserModel.php(332): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\User))
#10 X:\00.templates\ci4-starter\dist\app\Database\Seeds\UserSeeder.php(47): CodeIgniter\Shield\Models\UserModel->save(Object(CodeIgniter\Shield\Entities\User))
#11 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\Seeder.php(147): App\Database\Seeds\UserSeeder->run()
#12 X:\00.templates\ci4-starter\dist\app\Database\Seeds\A1Seeder.php(11): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#13 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\Seeder.php(147): App\Database\Seeds\A1Seeder->run()
#14 X:\00.templates\ci4-starter\dist\app\Database\Seeds\BaseSeeder.php(13): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#15 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\Seeder.php(147): App\Database\Seeds\BaseSeeder->run()
#16 X:\00.templates\ci4-starter\dist\app\Commands\RefreshCommand.php(63): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#17 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\CLI\Commands.php(70): App\Commands\RefreshCommand->run(Array)
#18 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('starter:refresh', Array)
#19 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Boot.php(351): CodeIgniter\CLI\Console->run()
#20 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#21 X:\00.templates\ci4-starter\dist\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#22 {main}
CRITICAL - 2024-11-25 09:21:21 --> CodeIgniter\Database\Exceptions\DatabaseException: Table '808_starter.users' doesn't exist
[Method: CLI, Route: starter:refresh]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `created_at`, `updated_at`) VALUES (:username:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 VENDORPATH\codeigniter4\shield\src\Models\UserModel.php(270): CodeIgniter\Model->insert(Object(CodeIgniter\Shield\Entities\User), false)
 6 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Shield\Models\UserModel->insert(Object(CodeIgniter\Shield\Entities\User), false)
 7 VENDORPATH\codeigniter4\shield\src\Models\UserModel.php(332): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\User))
 8 APPPATH\Database\Seeds\UserSeeder.php(47): CodeIgniter\Shield\Models\UserModel->save(Object(CodeIgniter\Shield\Entities\User))
 9 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\UserSeeder->run()
10 APPPATH\Database\Seeds\A1Seeder.php(11): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\UserSeeder')
11 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\A1Seeder->run()
12 APPPATH\Database\Seeds\BaseSeeder.php(13): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\A1Seeder')
13 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\BaseSeeder->run()
14 APPPATH\Commands\RefreshCommand.php(63): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\BaseSeeder')
15 SYSTEMPATH\CLI\Commands.php(70): App\Commands\RefreshCommand->run([])
16 SYSTEMPATH\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('starter:refresh', [])
17 SYSTEMPATH\Boot.php(351): CodeIgniter\CLI\Console->run()
18 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
19 ROOTPATH\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
CRITICAL - 2024-11-25 09:21:21 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table '808_starter.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `created_at`, `updated_at`) VALUES (\'JayLamping\', \'2024-11-25 09:21:21\', \'2024-11-25 09:21:21\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `created_at`, `updated_at`) VALUES (\'JayLamping\', \'2024-11-25 09:21:21\', \'2024-11-25 09:21:21\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `created_at`, `updated_at`) VALUES (:username:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 VENDORPATH\codeigniter4\shield\src\Models\UserModel.php(270): CodeIgniter\Model->insert(Object(CodeIgniter\Shield\Entities\User), false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Shield\Models\UserModel->insert(Object(CodeIgniter\Shield\Entities\User), false)
 9 VENDORPATH\codeigniter4\shield\src\Models\UserModel.php(332): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\User))
10 APPPATH\Database\Seeds\UserSeeder.php(47): CodeIgniter\Shield\Models\UserModel->save(Object(CodeIgniter\Shield\Entities\User))
11 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\UserSeeder->run()
12 APPPATH\Database\Seeds\A1Seeder.php(11): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\UserSeeder')
13 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\A1Seeder->run()
14 APPPATH\Database\Seeds\BaseSeeder.php(13): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\A1Seeder')
15 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\BaseSeeder->run()
16 APPPATH\Commands\RefreshCommand.php(63): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\BaseSeeder')
17 SYSTEMPATH\CLI\Commands.php(70): App\Commands\RefreshCommand->run([])
18 SYSTEMPATH\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('starter:refresh', [])
19 SYSTEMPATH\Boot.php(351): CodeIgniter\CLI\Console->run()
20 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
21 ROOTPATH\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
CRITICAL - 2024-11-25 09:21:21 --> [Caused by] mysqli_sql_exception: Table '808_starter.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `users` (`username`, `created_at`, `updated_at`) VALUES (\'JayLamping\', \'2024-11-25 09:21:21\', \'2024-11-25 09:21:21\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `created_at`, `updated_at`) VALUES (\'JayLamping\', \'2024-11-25 09:21:21\', \'2024-11-25 09:21:21\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `created_at`, `updated_at`) VALUES (\'JayLamping\', \'2024-11-25 09:21:21\', \'2024-11-25 09:21:21\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `created_at`, `updated_at`) VALUES (:username:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 VENDORPATH\codeigniter4\shield\src\Models\UserModel.php(270): CodeIgniter\Model->insert(Object(CodeIgniter\Shield\Entities\User), false)
 9 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Shield\Models\UserModel->insert(Object(CodeIgniter\Shield\Entities\User), false)
10 VENDORPATH\codeigniter4\shield\src\Models\UserModel.php(332): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\User))
11 APPPATH\Database\Seeds\UserSeeder.php(47): CodeIgniter\Shield\Models\UserModel->save(Object(CodeIgniter\Shield\Entities\User))
12 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\UserSeeder->run()
13 APPPATH\Database\Seeds\A1Seeder.php(11): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\UserSeeder')
14 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\A1Seeder->run()
15 APPPATH\Database\Seeds\BaseSeeder.php(13): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\A1Seeder')
16 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\BaseSeeder->run()
17 APPPATH\Commands\RefreshCommand.php(63): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\BaseSeeder')
18 SYSTEMPATH\CLI\Commands.php(70): App\Commands\RefreshCommand->run([])
19 SYSTEMPATH\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('starter:refresh', [])
20 SYSTEMPATH\Boot.php(351): CodeIgniter\CLI\Console->run()
21 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
22 ROOTPATH\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
ERROR - 2024-11-25 09:22:35 --> mysqli_sql_exception: Table 'news_ratings' already exists in X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(312): mysqli->query('CREATE TABLE `n...', 0)
#1 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `n...')
#2 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `n...')
#3 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `n...')
#4 X:\00.templates\ci4-starter\dist\Modules\Blog\Database\Migrations\2024-11-25-085502_News.php(124): CodeIgniter\Database\Forge->createTable('news_ratings')
#5 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(867): Blogs\Database\Migrations\News->up()
#6 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(183): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Boot.php(351): CodeIgniter\CLI\Console->run()
#11 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 X:\00.templates\ci4-starter\dist\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2024-11-25 09:29:00 --> mysqli_sql_exception: Table 'news_tags' already exists in X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(312): mysqli->query('CREATE TABLE `n...', 0)
#1 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `n...')
#2 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `n...')
#3 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `n...')
#4 X:\00.templates\ci4-starter\dist\Modules\Blog\Database\Migrations\2024-11-25-085502_News.php(136): CodeIgniter\Database\Forge->createTable('news_tags')
#5 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(867): Blogs\Database\Migrations\News->up()
#6 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(183): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Boot.php(351): CodeIgniter\CLI\Console->run()
#11 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 X:\00.templates\ci4-starter\dist\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2024-11-25 19:16:05 --> mysqli_sql_exception: Unknown column 'phone' in 'field list' in X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `us...', 0)
#1 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\shield\src\Models\UserModel.php(270): CodeIgniter\Model->insert(Object(CodeIgniter\Shield\Entities\User), false)
#8 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Shield\Models\UserModel->insert(Object(CodeIgniter\Shield\Entities\User), false)
#9 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\shield\src\Models\UserModel.php(332): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\User))
#10 X:\00.templates\ci4-starter\dist\app\Database\Seeds\UserSeeder.php(47): CodeIgniter\Shield\Models\UserModel->save(Object(CodeIgniter\Shield\Entities\User))
#11 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\Seeder.php(147): App\Database\Seeds\UserSeeder->run()
#12 X:\00.templates\ci4-starter\dist\app\Database\Seeds\A1Seeder.php(11): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#13 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\Seeder.php(147): App\Database\Seeds\A1Seeder->run()
#14 X:\00.templates\ci4-starter\dist\app\Database\Seeds\BaseSeeder.php(13): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#15 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\Seeder.php(147): App\Database\Seeds\BaseSeeder->run()
#16 X:\00.templates\ci4-starter\dist\app\Commands\Install.php(81): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#17 X:\00.templates\ci4-starter\dist\app\Commands\Install.php(53): App\Commands\Install->runSeeder()
#18 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\CLI\Commands.php(70): App\Commands\Install->run(Array)
#19 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('starter:install', Array)
#20 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Boot.php(351): CodeIgniter\CLI\Console->run()
#21 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#22 X:\00.templates\ci4-starter\dist\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#23 {main}
CRITICAL - 2024-11-25 19:16:05 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'phone' in 'field list'
[Method: CLI, Route: starter:install]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `first_name`, `last_name`, `dob`, `client_id`, `description`, `avatar`, `image`, `phone`, `mobile_number`, `message_checked_at`, `notification_checked_at`, `job_title`, `user_type`, `note`, `sticky_note`, `enable_web_notification`, `enable_email_notification`, `whatsapp`, `instagram`, `facebook`, `twitter`, `linked_in`, `skype`, `tiktok`, `created_at`, `updated_at`) VALUES (:username:, :first_name:, :last_name:, :dob:, :client_id:, :description:, :avatar:, :image:, :phone:, :mobile_number:, :message_checked_at:, :notification_checked_at:, :job_title:, :user_type:, :note:, :sticky_note:, :enable_web_notification:, :enable_email_notification:, :whatsapp:, :instagram:, :facebook:, :twitter:, :linked_in:, :skype:, :tiktok:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 VENDORPATH\codeigniter4\shield\src\Models\UserModel.php(270): CodeIgniter\Model->insert(Object(CodeIgniter\Shield\Entities\User), false)
 6 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Shield\Models\UserModel->insert(Object(CodeIgniter\Shield\Entities\User), false)
 7 VENDORPATH\codeigniter4\shield\src\Models\UserModel.php(332): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\User))
 8 APPPATH\Database\Seeds\UserSeeder.php(47): CodeIgniter\Shield\Models\UserModel->save(Object(CodeIgniter\Shield\Entities\User))
 9 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\UserSeeder->run()
10 APPPATH\Database\Seeds\A1Seeder.php(11): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\UserSeeder')
11 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\A1Seeder->run()
12 APPPATH\Database\Seeds\BaseSeeder.php(13): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\A1Seeder')
13 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\BaseSeeder->run()
14 APPPATH\Commands\Install.php(81): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\BaseSeeder')
15 APPPATH\Commands\Install.php(53): App\Commands\Install->runSeeder()
16 SYSTEMPATH\CLI\Commands.php(70): App\Commands\Install->run([])
17 SYSTEMPATH\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('starter:install', [])
18 SYSTEMPATH\Boot.php(351): CodeIgniter\CLI\Console->run()
19 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
20 ROOTPATH\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
CRITICAL - 2024-11-25 19:16:05 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'phone' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `first_name`, `last_name`, `dob`, `client_id`, `description`, `avatar`, `image`, `phone`, `mobile_number`, `message_checked_at`, `notification_checked_at`, `job_title`, `user_type`, `note`, `sticky_note`, `enable_web_notification`, `enable_email_notification`, `whatsapp`, `instagram`, `facebook`, `twitter`, `linked_in`, `skype`, `tiktok`, `created_at`, `updated_at`) VALUES (\'JayLamping\', \'John\', \'Lamping\', \'1963-03-07\', \'1050\', \'no desc yet\', \'01.png\', \'bg-profile-default.jpg\', \'8087251900\', \'8585551212\', \'\', \'\', \'President\', \'staff\', \'add a better note here\', \'add a better sticky note here\', \'1\', \'1\', \'@808biz\', \'@808biz\', \'@808biz\', \'@808biz\', \'@808biz\', \'@808biz\', \'@808biz\', \'2024-11-25 19:16:05\', \'2024-11-25 19:16:05\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `first_name`, `last_name`, `dob`, `client_id`, `description`, `avatar`, `image`, `phone`, `mobile_number`, `message_checked_at`, `notification_checked_at`, `job_title`, `user_type`, `note`, `sticky_note`, `enable_web_notification`, `enable_email_notification`, `whatsapp`, `instagram`, `facebook`, `twitter`, `linked_in`, `skype`, `tiktok`, `created_at`, `updated_at`) VALUES (\'JayLamping\', \'John\', \'Lamping\', \'1963-03-07\', \'1050\', \'no desc yet\', \'01.png\', \'bg-profile-default.jpg\', \'8087251900\', \'8585551212\', \'\', \'\', \'President\', \'staff\', \'add a better note here\', \'add a better sticky note here\', \'1\', \'1\', \'@808biz\', \'@808biz\', \'@808biz\', \'@808biz\', \'@808biz\', \'@808biz\', \'@808biz\', \'2024-11-25 19:16:05\', \'2024-11-25 19:16:05\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `first_name`, `last_name`, `dob`, `client_id`, `description`, `avatar`, `image`, `phone`, `mobile_number`, `message_checked_at`, `notification_checked_at`, `job_title`, `user_type`, `note`, `sticky_note`, `enable_web_notification`, `enable_email_notification`, `whatsapp`, `instagram`, `facebook`, `twitter`, `linked_in`, `skype`, `tiktok`, `created_at`, `updated_at`) VALUES (:username:, :first_name:, :last_name:, :dob:, :client_id:, :description:, :avatar:, :image:, :phone:, :mobile_number:, :message_checked_at:, :notification_checked_at:, :job_title:, :user_type:, :note:, :sticky_note:, :enable_web_notification:, :enable_email_notification:, :whatsapp:, :instagram:, :facebook:, :twitter:, :linked_in:, :skype:, :tiktok:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 VENDORPATH\codeigniter4\shield\src\Models\UserModel.php(270): CodeIgniter\Model->insert(Object(CodeIgniter\Shield\Entities\User), false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Shield\Models\UserModel->insert(Object(CodeIgniter\Shield\Entities\User), false)
 9 VENDORPATH\codeigniter4\shield\src\Models\UserModel.php(332): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\User))
10 APPPATH\Database\Seeds\UserSeeder.php(47): CodeIgniter\Shield\Models\UserModel->save(Object(CodeIgniter\Shield\Entities\User))
11 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\UserSeeder->run()
12 APPPATH\Database\Seeds\A1Seeder.php(11): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\UserSeeder')
13 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\A1Seeder->run()
14 APPPATH\Database\Seeds\BaseSeeder.php(13): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\A1Seeder')
15 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\BaseSeeder->run()
16 APPPATH\Commands\Install.php(81): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\BaseSeeder')
17 APPPATH\Commands\Install.php(53): App\Commands\Install->runSeeder()
18 SYSTEMPATH\CLI\Commands.php(70): App\Commands\Install->run([])
19 SYSTEMPATH\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('starter:install', [])
20 SYSTEMPATH\Boot.php(351): CodeIgniter\CLI\Console->run()
21 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
22 ROOTPATH\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
CRITICAL - 2024-11-25 19:16:05 --> [Caused by] mysqli_sql_exception: Unknown column 'phone' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `users` (`username`, `first_name`, `last_name`, `dob`, `client_id`, `description`, `avatar`, `image`, `phone`, `mobile_number`, `message_checked_at`, `notification_checked_at`, `job_title`, `user_type`, `note`, `sticky_note`, `enable_web_notification`, `enable_email_notification`, `whatsapp`, `instagram`, `facebook`, `twitter`, `linked_in`, `skype`, `tiktok`, `created_at`, `updated_at`) VALUES (\'JayLamping\', \'John\', \'Lamping\', \'1963-03-07\', \'1050\', \'no desc yet\', \'01.png\', \'bg-profile-default.jpg\', \'8087251900\', \'8585551212\', \'\', \'\', \'President\', \'staff\', \'add a better note here\', \'add a better sticky note here\', \'1\', \'1\', \'@808biz\', \'@808biz\', \'@808biz\', \'@808biz\', \'@808biz\', \'@808biz\', \'@808biz\', \'2024-11-25 19:16:05\', \'2024-11-25 19:16:05\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `first_name`, `last_name`, `dob`, `client_id`, `description`, `avatar`, `image`, `phone`, `mobile_number`, `message_checked_at`, `notification_checked_at`, `job_title`, `user_type`, `note`, `sticky_note`, `enable_web_notification`, `enable_email_notification`, `whatsapp`, `instagram`, `facebook`, `twitter`, `linked_in`, `skype`, `tiktok`, `created_at`, `updated_at`) VALUES (\'JayLamping\', \'John\', \'Lamping\', \'1963-03-07\', \'1050\', \'no desc yet\', \'01.png\', \'bg-profile-default.jpg\', \'8087251900\', \'8585551212\', \'\', \'\', \'President\', \'staff\', \'add a better note here\', \'add a better sticky note here\', \'1\', \'1\', \'@808biz\', \'@808biz\', \'@808biz\', \'@808biz\', \'@808biz\', \'@808biz\', \'@808biz\', \'2024-11-25 19:16:05\', \'2024-11-25 19:16:05\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `first_name`, `last_name`, `dob`, `client_id`, `description`, `avatar`, `image`, `phone`, `mobile_number`, `message_checked_at`, `notification_checked_at`, `job_title`, `user_type`, `note`, `sticky_note`, `enable_web_notification`, `enable_email_notification`, `whatsapp`, `instagram`, `facebook`, `twitter`, `linked_in`, `skype`, `tiktok`, `created_at`, `updated_at`) VALUES (\'JayLamping\', \'John\', \'Lamping\', \'1963-03-07\', \'1050\', \'no desc yet\', \'01.png\', \'bg-profile-default.jpg\', \'8087251900\', \'8585551212\', \'\', \'\', \'President\', \'staff\', \'add a better note here\', \'add a better sticky note here\', \'1\', \'1\', \'@808biz\', \'@808biz\', \'@808biz\', \'@808biz\', \'@808biz\', \'@808biz\', \'@808biz\', \'2024-11-25 19:16:05\', \'2024-11-25 19:16:05\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `first_name`, `last_name`, `dob`, `client_id`, `description`, `avatar`, `image`, `phone`, `mobile_number`, `message_checked_at`, `notification_checked_at`, `job_title`, `user_type`, `note`, `sticky_note`, `enable_web_notification`, `enable_email_notification`, `whatsapp`, `instagram`, `facebook`, `twitter`, `linked_in`, `skype`, `tiktok`, `created_at`, `updated_at`) VALUES (:username:, :first_name:, :last_name:, :dob:, :client_id:, :description:, :avatar:, :image:, :phone:, :mobile_number:, :message_checked_at:, :notification_checked_at:, :job_title:, :user_type:, :note:, :sticky_note:, :enable_web_notification:, :enable_email_notification:, :whatsapp:, :instagram:, :facebook:, :twitter:, :linked_in:, :skype:, :tiktok:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 VENDORPATH\codeigniter4\shield\src\Models\UserModel.php(270): CodeIgniter\Model->insert(Object(CodeIgniter\Shield\Entities\User), false)
 9 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Shield\Models\UserModel->insert(Object(CodeIgniter\Shield\Entities\User), false)
10 VENDORPATH\codeigniter4\shield\src\Models\UserModel.php(332): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\User))
11 APPPATH\Database\Seeds\UserSeeder.php(47): CodeIgniter\Shield\Models\UserModel->save(Object(CodeIgniter\Shield\Entities\User))
12 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\UserSeeder->run()
13 APPPATH\Database\Seeds\A1Seeder.php(11): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\UserSeeder')
14 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\A1Seeder->run()
15 APPPATH\Database\Seeds\BaseSeeder.php(13): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\A1Seeder')
16 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\BaseSeeder->run()
17 APPPATH\Commands\Install.php(81): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\BaseSeeder')
18 APPPATH\Commands\Install.php(53): App\Commands\Install->runSeeder()
19 SYSTEMPATH\CLI\Commands.php(70): App\Commands\Install->run([])
20 SYSTEMPATH\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('starter:install', [])
21 SYSTEMPATH\Boot.php(351): CodeIgniter\CLI\Console->run()
22 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
23 ROOTPATH\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
CRITICAL - 2024-11-25 19:26:15 --> ErrorException: Cannot declare class App\Database\Seeds\UserSeeder1, because the name is already in use
[Method: CLI, Route: starter:install]
in APPPATH\Database\Seeds\UserSeeder.php on line 8.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2024-11-25 19:27:20 --> mysqli_sql_exception: Unknown column 'user_id' in 'field list' in X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `no...', 0)
#1 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `no...')
#2 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `no...')
#3 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `no...', Array, false)
#4 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 X:\00.templates\ci4-starter\dist\app\Models\UserModel.php(101): CodeIgniter\Model->insert(Array)
#8 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\BaseModel.php(1698): App\Models\UserModel->createNotificationSettings(Array)
#9 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\BaseModel.php(850): CodeIgniter\BaseModel->trigger('afterInsert', Array)
#10 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#11 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\shield\src\Models\UserModel.php(270): CodeIgniter\Model->insert(Object(App\Entities\User), false)
#12 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Shield\Models\UserModel->insert(Object(App\Entities\User), false)
#13 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\shield\src\Models\UserModel.php(332): CodeIgniter\BaseModel->save(Object(App\Entities\User))
#14 X:\00.templates\ci4-starter\dist\app\Database\Seeds\UserSeeder.php(45): CodeIgniter\Shield\Models\UserModel->save(Object(App\Entities\User))
#15 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\Seeder.php(147): App\Database\Seeds\UserSeeder->run()
#16 X:\00.templates\ci4-starter\dist\app\Database\Seeds\A1Seeder.php(11): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#17 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\Seeder.php(147): App\Database\Seeds\A1Seeder->run()
#18 X:\00.templates\ci4-starter\dist\app\Database\Seeds\BaseSeeder.php(13): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#19 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Database\Seeder.php(147): App\Database\Seeds\BaseSeeder->run()
#20 X:\00.templates\ci4-starter\dist\app\Commands\Install.php(81): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#21 X:\00.templates\ci4-starter\dist\app\Commands\Install.php(53): App\Commands\Install->runSeeder()
#22 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\CLI\Commands.php(70): App\Commands\Install->run(Array)
#23 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('starter:install', Array)
#24 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Boot.php(351): CodeIgniter\CLI\Console->run()
#25 X:\00.templates\ci4-starter\dist\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#26 X:\00.templates\ci4-starter\dist\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#27 {main}
CRITICAL - 2024-11-25 19:27:20 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'user_id' in 'field list'
[Method: CLI, Route: starter:install]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `notification_settings` (`user_id`, `created_at`, `updated_at`) VALUES (:user_id:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Models\UserModel.php(101): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\BaseModel.php(1698): App\Models\UserModel->createNotificationSettings([...])
 7 SYSTEMPATH\BaseModel.php(850): CodeIgniter\BaseModel->trigger('afterInsert', [...])
 8 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 9 VENDORPATH\codeigniter4\shield\src\Models\UserModel.php(270): CodeIgniter\Model->insert(Object(App\Entities\User), false)
10 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Shield\Models\UserModel->insert(Object(App\Entities\User), false)
11 VENDORPATH\codeigniter4\shield\src\Models\UserModel.php(332): CodeIgniter\BaseModel->save(Object(App\Entities\User))
12 APPPATH\Database\Seeds\UserSeeder.php(45): CodeIgniter\Shield\Models\UserModel->save(Object(App\Entities\User))
13 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\UserSeeder->run()
14 APPPATH\Database\Seeds\A1Seeder.php(11): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\UserSeeder')
15 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\A1Seeder->run()
16 APPPATH\Database\Seeds\BaseSeeder.php(13): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\A1Seeder')
17 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\BaseSeeder->run()
18 APPPATH\Commands\Install.php(81): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\BaseSeeder')
19 APPPATH\Commands\Install.php(53): App\Commands\Install->runSeeder()
20 SYSTEMPATH\CLI\Commands.php(70): App\Commands\Install->run([])
21 SYSTEMPATH\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('starter:install', [])
22 SYSTEMPATH\Boot.php(351): CodeIgniter\CLI\Console->run()
23 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
24 ROOTPATH\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
CRITICAL - 2024-11-25 19:27:20 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'user_id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `notification_settings` (`user_id`, `created_at`, `updated_at`) VALUES (1, \'2024-11-25 19:27:20\', \'2024-11-25 19:27:20\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `notification_settings` (`user_id`, `created_at`, `updated_at`) VALUES (1, \'2024-11-25 19:27:20\', \'2024-11-25 19:27:20\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `notification_settings` (`user_id`, `created_at`, `updated_at`) VALUES (:user_id:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Models\UserModel.php(101): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\BaseModel.php(1698): App\Models\UserModel->createNotificationSettings([...])
 9 SYSTEMPATH\BaseModel.php(850): CodeIgniter\BaseModel->trigger('afterInsert', [...])
10 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
11 VENDORPATH\codeigniter4\shield\src\Models\UserModel.php(270): CodeIgniter\Model->insert(Object(App\Entities\User), false)
12 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Shield\Models\UserModel->insert(Object(App\Entities\User), false)
13 VENDORPATH\codeigniter4\shield\src\Models\UserModel.php(332): CodeIgniter\BaseModel->save(Object(App\Entities\User))
14 APPPATH\Database\Seeds\UserSeeder.php(45): CodeIgniter\Shield\Models\UserModel->save(Object(App\Entities\User))
15 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\UserSeeder->run()
16 APPPATH\Database\Seeds\A1Seeder.php(11): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\UserSeeder')
17 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\A1Seeder->run()
18 APPPATH\Database\Seeds\BaseSeeder.php(13): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\A1Seeder')
19 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\BaseSeeder->run()
20 APPPATH\Commands\Install.php(81): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\BaseSeeder')
21 APPPATH\Commands\Install.php(53): App\Commands\Install->runSeeder()
22 SYSTEMPATH\CLI\Commands.php(70): App\Commands\Install->run([])
23 SYSTEMPATH\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('starter:install', [])
24 SYSTEMPATH\Boot.php(351): CodeIgniter\CLI\Console->run()
25 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
26 ROOTPATH\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
CRITICAL - 2024-11-25 19:27:20 --> [Caused by] mysqli_sql_exception: Unknown column 'user_id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `notification_settings` (`user_id`, `created_at`, `updated_at`) VALUES (1, \'2024-11-25 19:27:20\', \'2024-11-25 19:27:20\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `notification_settings` (`user_id`, `created_at`, `updated_at`) VALUES (1, \'2024-11-25 19:27:20\', \'2024-11-25 19:27:20\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `notification_settings` (`user_id`, `created_at`, `updated_at`) VALUES (1, \'2024-11-25 19:27:20\', \'2024-11-25 19:27:20\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `notification_settings` (`user_id`, `created_at`, `updated_at`) VALUES (:user_id:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\UserModel.php(101): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\BaseModel.php(1698): App\Models\UserModel->createNotificationSettings([...])
10 SYSTEMPATH\BaseModel.php(850): CodeIgniter\BaseModel->trigger('afterInsert', [...])
11 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
12 VENDORPATH\codeigniter4\shield\src\Models\UserModel.php(270): CodeIgniter\Model->insert(Object(App\Entities\User), false)
13 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Shield\Models\UserModel->insert(Object(App\Entities\User), false)
14 VENDORPATH\codeigniter4\shield\src\Models\UserModel.php(332): CodeIgniter\BaseModel->save(Object(App\Entities\User))
15 APPPATH\Database\Seeds\UserSeeder.php(45): CodeIgniter\Shield\Models\UserModel->save(Object(App\Entities\User))
16 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\UserSeeder->run()
17 APPPATH\Database\Seeds\A1Seeder.php(11): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\UserSeeder')
18 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\A1Seeder->run()
19 APPPATH\Database\Seeds\BaseSeeder.php(13): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\A1Seeder')
20 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\BaseSeeder->run()
21 APPPATH\Commands\Install.php(81): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\BaseSeeder')
22 APPPATH\Commands\Install.php(53): App\Commands\Install->runSeeder()
23 SYSTEMPATH\CLI\Commands.php(70): App\Commands\Install->run([])
24 SYSTEMPATH\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('starter:install', [])
25 SYSTEMPATH\Boot.php(351): CodeIgniter\CLI\Console->run()
26 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
27 ROOTPATH\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
CRITICAL - 2024-11-25 19:56:14 --> Error: Call to a member function insert() on null
[Method: CLI, Route: starter:install]
in APPPATH\Database\Seeds\DownloadsSeeder.php on line 95.
 1 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\DownloadsSeeder->run()
 2 APPPATH\Database\Seeds\A1Seeder.php(12): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\DownloadsSeeder')
 3 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\A1Seeder->run()
 4 APPPATH\Database\Seeds\BaseSeeder.php(13): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\A1Seeder')
 5 SYSTEMPATH\Database\Seeder.php(147): App\Database\Seeds\BaseSeeder->run()
 6 APPPATH\Commands\Install.php(81): CodeIgniter\Database\Seeder->call('App\\Database\\Seeds\\BaseSeeder')
 7 APPPATH\Commands\Install.php(53): App\Commands\Install->runSeeder()
 8 SYSTEMPATH\CLI\Commands.php(70): App\Commands\Install->run([])
 9 SYSTEMPATH\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('starter:install', [])
10 SYSTEMPATH\Boot.php(351): CodeIgniter\CLI\Console->run()
11 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
12 ROOTPATH\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
CRITICAL - 2024-11-25 21:07:19 --> Error: Call to undefined function Blogs\Database\Seeds\slug()
[Method: CLI, Route: starter:install]
in ROOTPATH\Modules\Blog\Database\Seeds\NewsSeeder.php on line 61.
 1 ROOTPATH\Modules\Blog\Database\Seeds\NewsSeeder.php(30): Blogs\Database\Seeds\NewsSeeder->generatePost([...], [...], [...])
 2 SYSTEMPATH\Database\Seeder.php(147): Blogs\Database\Seeds\NewsSeeder->run()
 3 ROOTPATH\Modules\Blog\Database\Seeds\BlogSeeder.php(14): CodeIgniter\Database\Seeder->call('Blogs\\Database\\Seeds\\NewsSeeder')
 4 SYSTEMPATH\Database\Seeder.php(147): Blogs\Database\Seeds\BlogSeeder->run()
 5 APPPATH\Commands\Install.php(87): CodeIgniter\Database\Seeder->call('Blogs\\Database\\Seeds\\BlogSeeder')
 6 APPPATH\Commands\Install.php(53): App\Commands\Install->runSeeder()
 7 SYSTEMPATH\CLI\Commands.php(70): App\Commands\Install->run([])
 8 SYSTEMPATH\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('starter:install', [])
 9 SYSTEMPATH\Boot.php(351): CodeIgniter\CLI\Console->run()
10 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
11 ROOTPATH\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
CRITICAL - 2024-11-25 21:09:37 --> ErrorException: Allowed memory size of 134217728 bytes exhausted (tried to allocate 528384 bytes)
[Method: CLI, Route: starter:install]
in VENDORPATH\fakerphp\faker\src\Faker\Provider\Text.php on line 142.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
